# Generated by Django 4.0.1 on 2022-01-08 20:15

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0002_alter_inventory_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('warehouse_name', models.CharField(max_length=200)),
            ],
            options={
                'ordering': ['warehouse_name'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('price', models.DecimalField(decimal_places=2, max_digits=17)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AlterModelOptions(
            name='inventory',
            options={'ordering': ['product']},
        ),
        migrations.RemoveField(
            model_name='inventory',
            name='name',
        ),
        migrations.RemoveField(
            model_name='inventory',
            name='price',
        ),
        migrations.AlterField(
            model_name='inventory',
            name='stock',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='Shelf',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('shelf_name', models.CharField(max_length=200)),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crud.location')),
            ],
            options={
                'ordering': ['shelf_name'],
            },
        ),
        migrations.AddField(
            model_name='inventory',
            name='product',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='crud.product'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='inventory',
            name='shelf',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='crud.shelf'),
            preserve_default=False,
        ),
    ]
