# Generated by Django 4.0.1 on 2022-01-10 20:23

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0004_alter_product_price'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inventory',
            options={'ordering': ['product'], 'verbose_name': 'inventory item'},
        ),
        migrations.AlterModelOptions(
            name='location',
            options={'ordering': ['warehouse_name'], 'verbose_name': 'location'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['name'], 'verbose_name': 'product'},
        ),
        migrations.AlterModelOptions(
            name='shelf',
            options={'ordering': ['shelf_name'], 'verbose_name': 'shelf', 'verbose_name_plural': 'shelves'},
        ),
        migrations.AlterField(
            model_name='inventory',
            name='product',
            field=models.ForeignKey(help_text='The product contained in the inventory.', on_delete=django.db.models.deletion.CASCADE, to='crud.product'),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='shelf',
            field=models.ForeignKey(help_text='The shelf that this inventory is stored on.', on_delete=django.db.models.deletion.CASCADE, to='crud.shelf'),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='stock',
            field=models.PositiveIntegerField(default=0, help_text='The amount of product available in this inventory.'),
        ),
        migrations.AlterField(
            model_name='location',
            name='warehouse_name',
            field=models.CharField(help_text='Name of the warehouse.', max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(help_text='Name of the product', max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, help_text='Current price of the product.', max_digits=17, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
        migrations.AlterField(
            model_name='shelf',
            name='shelf_name',
            field=models.CharField(help_text="Name the storage shelf. Should describe where it's located in the warehouse.", max_length=200),
        ),
        migrations.AlterField(
            model_name='shelf',
            name='warehouse',
            field=models.ForeignKey(help_text='The warehouse where this shelf is located.', on_delete=django.db.models.deletion.CASCADE, to='crud.location'),
        ),
    ]
